### ISSUE TITLE
Open Standards for Community Participation

### ISSUE THREAD

**Issue by GitRengeki** [Scode-Community/Community-Website#8]
### I reviewed the source code for the project, and here's what I thought:

At first glance, the project has no open standards on how developers should contribute. I see that the project is relatively new, but with scaling in mind, this source code is hard to maintain over time. 

I propose to make a "how to contribute" panel in the README for student developers to get a headstart. It should contain HOW-TOs on producing good codes with readability and efficiency.

**Comment by Harleythetech** [comment]
thanks for opening this issue, we will be discuss this and once approved then we will improve the `README`.

For me this suggestion is good but i also need to consult to the maker since my skills in coding is what you see on my last contribution, In terms of the `How to Contribute` this will be implemented.

**Comment by Harleythetech** [comment]
Kindly Check the `README.md` and tell me if that is ok!

**Comment by GitRengeki** [comment]
> Kindly Check the `README.md` and tell me if that is ok!

I think the revision on `README.md` will do just fine for now. 

> if you have any adjustments in mind please fetch the latest upstream and modify the readme.md and contribute.

Thanks, I'll contribute when I have some time.

**Comment by Harleythetech** [comment]
Closing this as the issue has been resolved.

**Comment by Harleythetech** [comment]
oh lastly you are now a moderator here and also can you give me your discord id? if you don't mind i'd like to have some opinions on your side.

**Comment by GitRengeki** [comment]
my discord user is Rengeki, I'm in the Scode Community server.
